name = 'Koralyte'
license = 'MIT'
licenselink = 'https://github.com/ragibson/koralyte/blob/main/LICENSE'
description = 'An elegant, minimalist Hugo theme for creating clean websites and blogs.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/ragibson/koralyte'

# A running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ["blog", "personal", "minimal", "elegant", "responsive", "simple", "clean", "minimalist", "dark mode"]
features = ["responsive", "blog", "table-of-contents", "social-icons", "code-blocks", "customization", "dark mode"]

# If the theme has a single author
[author]
  name = 'Ryan Gibson'
  homepage = 'https://ryanagibson.com'