# Koralyte theme for Hugo
name = "Koralyte"
license = "MIT"
licenselink = "https://github.com/ragibson/koralyte/blob/main/LICENSE"
description = "An elegant, minimalist Hugo theme for creating clean websites and blogs."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/ragibson/koralyte"

tags = ["blog", "minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["syntax highlighting", "dark mode", "emoji", "client-side search", "Tailwind CSS", "responsive", "KaTeX", "YouTube embeds"]

[author]
  name = "Ryan Gibson"
  homepage = "https://ryanagibson.com"
